### ISSUE TITLE
New message emails – add an option for increased frequency

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#16]
My suggestion would be `Every few hours` or something relatively benign sounding. And I think we should set that to 4 hour intervals and make this the default setting. 

Rational: People will want to respond to new posts. Once per day you will miss all the action. 4 hours is the right amount of time, but people won't want to opt into this time interval because it sounds like too much. But it won't be, it will feel just right to people are really engaged.

**Comment by GInxh** [comment]
@jeffdomke can you label these with label, assign them to a project or an epic. If noone is assigned or these aren't triaged they will go into a two year backlog. I want to minimize doing this for issues opened by Blockstack employees and only do so for opensource issues. Same for other two issues opened today. Thanks!

**Comment by jeffdomke** [comment]
This option should be set to the default please.
