### ISSUE TITLE
Prompt user to enter email upon first auth

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#2]
User can skip or dismiss

**Comment by jeffdomke** [comment]
This on staging? Didn't see it work?

**Comment by aulneau** [comment]
This has not been addressed yet. you can enter your email in settings.

**Comment by hstove** [comment]
I've never added anything right after auth, like this ticket describes. Only in settings. Can you be more specific about how you think this should work best?

Options:
- Have a form with one 'email' field at the top of the page
- Have a notice with a link to settings
- Have it show up continually until they dismiss, or only once?

**Comment by jeffdomke** [comment]
Sure, I think we could do some complex behavioral stuff, but assuming we want to avoid that. 

We have anyway to know this is the first auth for this ID? – Assuming yes. 
Show up continually until they dismiss – Only shows up that first time. 

- User signs in with Blockstack ID
- Modal appears. Copy says: 

> Banter is a super-social place for friends to 💩 on each other. You might miss out if Banter can't send you notifications... don't worry, you can always remove your email or limit notifications in the **Settings** tab. 

<Field for entering email> <Done> <Skip> 

- `Skip` closes modal
- `Done` closes modal and updates email. 

@aulneau this sound right to you?

**Comment by hstove** [comment]
Skip dismisses the modal forever, yes?

> Banter is a super-social place for friends to 💩 on each other.

Amazing.

**Comment by jeffdomke** [comment]
Skip dismisses the modal forever, yes? – Yes.

**Comment by aulneau** [comment]
This is resolved
