### ISSUE TITLE
ID menu names? 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#27]
![Screen Shot 2019-02-25 at 10:45 PM](http://marker.screenshots.prod.s3.amazonaws.com/e600caea29d84af1bd1c374c1ab83280-1551134745218.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202019-02-25%20at%205.43.03%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202019-02-25%20at%205.43.03%20PM.png)

**Comment by jeffdomke** [comment]
Not sure why it only populates certain IDs? I tried entering in new IDs and then retesting and it always displays the same IDs? Expecting it to contain all IDs I've used? Or most recent?

**Comment by hstove** [comment]
Is this a dup of #28 ? Check again and see what you think. It'll allow you to search for anyone who has every used Banter. Soon, you'll be able to search any blockstack ID.
