### ISSUE TITLE
Digest email formatting jank

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#31]
Number of weird formatting errors on different email clients. Would suggest being overly specific on all the css properties. This example is from Superhuman

![Screen Shot 2019-02-27 at 1.56.10 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/63e1df9b-40d3-4bd7-b403-dbd86a1e443a)

**Comment by hstove** [comment]
We are specific on background colors, but dark mode overrides them. It appears that there are some new CSS media queries that you can use to check for dark mode. I'll take a look tomorrow.

**Comment by jeffdomke** [comment]
![IMG_0056.PNG](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/4a7bf9fe-2874-451c-aaa6-9c82e5da95dd)

**Comment by jeffdomke** [comment]
Honestly, these email issues are so fraught with dumb complexity that I think we should consider plaintext as a solution. You can still mess with plaintext to deliver something nice. @aulneau and I have experience chasing our tails on this kind of junk, it is a nightmare.
