### ISSUE TITLE
On the fly invite copy

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#43]
![Screen Shot 2019-03-04 at 2:27 PM](http://marker.screenshots.prod.s3.amazonaws.com/634711d364604e0585ee94654a406719-1551709653257.png)

Suggest we upgrade the copy to something like: "Would you like to invite them via email? Otherwise, they probably won't ever see your message." 

---
### More Info

**Source URL**: [https://banter-radiks-staging-pr-41.herokuapp.com/](https://banter-radiks-staging-pr-41.herokuapp.com/)

**Comment by hstove** [comment]
done
