### ISSUE TITLE
Impose a character limit

### ISSUE THREAD

**Issue by hstove** [blockstack-radiks/banter#46]
140 or 280?

**Comment by aulneau** [comment]
I added one with #47 


![screen shot 2019-03-04 at 3 50 28 pm](https://user-images.githubusercontent.com/11803153/53765331-534b3e00-3e95-11e9-91a3-2634a7db95ef.png)

![screen shot 2019-03-04 at 3 50 20 pm](https://user-images.githubusercontent.com/11803153/53765330-534b3e00-3e95-11e9-9eed-2ab160bac9be.png)
