### ISSUE TITLE
Real time updates are lagging

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#56]
![Screen Shot 2019-03-05 at 3.02.15 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/2ea7a173-f636-480a-8c04-c39929f6367b)

**Comment by jeffdomke** [comment]
Likes on posts is updating in real time but new posts are coming in. Takes a refresh to get them.

**Comment by hstove** [comment]
Fixed by adding the 'update' notification. Not a perfect fix, but will fix at least tell you when you need to refresh.
