### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by hstove** [blockstack-radiks/banter#7]
- `/users/${name}`
- Pull profile details (name, avatar, etc)
- Display feed of user's posts
- Show 'not a Banter user', with `profile.json` data, if the user isn't in Radiks

Note to self for explorer-related data: the URL is https://blockstack-explorer-api.herokuapp.com/api/names/hankstoever.id

**Comment by aulneau** [comment]
you can find user profiles at `/[::]user.id`
